dial:
  dial:
    image:
      registry: ghcr.io
      repository: "intersect-dial/dial"
      tag: "main"

    configFile: |
      {
        "intersect": {
          "brokers": [
            {
              "username": "",
              "password": "",
              "host": "",
              "port": 123,
              "protocol": "mqtt3.1.1"
            }
          ]
        },
        "intersect-hierarchy": {
          "organization": "",
          "facility": "",
          "system": "",
          "subsystem": "",
          "service": ""
        },
        "dial": {
          "mongo": {
            "username": "",
            "password": "",
            "host": "",
            "port": 123
          }
        }
      }

  mongodb:
    enabled: true
    auth:
      enabled: true
      username: user
      password: ""
      rootPassword: ""
      database: mydb
